name:                dbms
version:             0.1.0.0
github:              "githubuser/dbms"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dbms#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring 
- cereal == 0.5.8.1
- transformers
- hashable == 1.3.0.0
# - utf8-string == 1.0.1.1
# - bytestring-conversion == 0.3.1

library:
  source-dirs: src

executables:
  dbms-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbms

tests:
  dbms-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbms
